[package]
name = "charlie"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
sqlx = { version = "0.6", features = ["sqlite", "runtime-tokio-rustls", "macros", "migrate"] }